# Generated by Django 3.2.6 on 2021-09-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='이름')),
                ('major', models.CharField(max_length=128, verbose_name='전공')),
            ],
            options={
                'verbose_name': '대학원 교수',
                'verbose_name_plural': '대학원 교수',
                'db_table': 'teacher',
            },
        ),
    ]
